import { useEffect, useState } from 'react';
import { coffees, type Coffee } from '../data/content';
import { beans, matchingBeans, roasters } from '../data/shelf';

function Arrow() { return <span className="ui-arrow" aria-hidden="true" />; }

export function ShelfTeaser() {
  return <section className="shelf-teaser section-shell" data-scroll>
    <div className="shelf-teaser-image"><img src="/shelf-beans.jpg" alt="An imagined still life of roasted beans in a ceramic bowl with a copper scoop" loading="lazy" width="1536" height="1024" /></div>
    <div data-reveal><p className="eyebrow">A little of the dream, at home</p><h2>Start with a bean.<br /><em>Make it your own.</em></h2><p>The café is still a dream. Your next lovely cup doesn’t have to wait. Wander through Indian roasters, find your roast, and bring a little ritual home.</p><a className="shelf-link" href="/shelf">Explore the coffee shelf <Arrow /></a><span className="shelf-caption">9 Indian sellers · Roast & grind guide</span></div>
  </section>;
}

export function BrewShelf({ coffee }: { coffee: Coffee }) {
  return <aside className="brew-shelf"><p className="eyebrow">Bring this ritual home</p><h3>Two beans to begin with.</h3><p>Our suggested directions for {coffee.name.toLowerCase()}. Choose <strong>{coffee.grind.toLowerCase()}</strong> ground coffee, or whole beans if you have a suitable grinder.</p><div>{matchingBeans(coffee).map(bean => <a key={bean.id} href={bean.url} target="_blank" rel="noreferrer"><span><small>{bean.seller} / {bean.roast}</small><strong>{bean.name}</strong></span><Arrow /></a>)}</div><a className="shelf-link" href={`/shelf?brew=${coffee.id}#beans`}>Find more on the coffee shelf <Arrow /></a><small>Independent suggestions; shop directly with the roaster. Links open a new tab.</small></aside>;
}

export function ShelfPage() {
  const initialBrew = new URLSearchParams(window.location.search).get('brew');
  const [brewId, setBrewId] = useState(coffees.some(c => c.id === initialBrew) ? initialBrew! : 'pour-over');
  const [roast, setRoast] = useState('all');
  const [seller, setSeller] = useState('all');
  const coffee = coffees.find(c => c.id === brewId)!;
  const visible = beans.filter(b => (roast === 'all' || b.tone === roast) && (seller === 'all' || b.seller === seller));
  const recommended = matchingBeans(coffee);
  const grind = coffee.grind.toLowerCase();
  const particleSize = grind.includes('extra-fine') ? 1 : grind.startsWith('coarse') ? 7 : grind.includes('coarse') ? 5 : grind.includes('medium') ? 3 : 2;
  useEffect(() => { document.title = 'The Coffee Shelf — CoffeeMasiha'; }, []);
  return <div className="shelf-page">
    <header className="shelf-header"><a className="brand" href="/"><span className="bean-mark" aria-hidden="true" />CoffeeMasiha</a><nav aria-label="Shelf navigation"><a href="/#dream">The dream</a><a href="#beans">The beans</a><a href="#grind">The grind</a><a href="#roasters">The roasters</a></nav></header>
    <section className="shelf-hero section-shell" id="top" data-scroll>
      <div className="shelf-hero-copy"><p className="eyebrow">The CoffeeMasiha shelf / India</p><h1>Bring the<br /><em>ritual home.</em></h1><p>A good cup starts long before the first sip.<br />With a bean, a little curiosity, and people who care.</p><a className="shelf-link" href="#beans">Find your next cup <Arrow /></a></div>
      <figure><img src="/shelf-beans.jpg" alt="Roasted beans, handmade ceramic and a copper scoop in warm window light" width="1536" height="1024" fetchPriority="high" /><figcaption>A study in simple things · AI-imagined still life</figcaption></figure>
      <div className="shelf-hero-foot"><span>Grown with care. Roasted with intention.</span><span>Coffee. Water. Your moment.</span></div>
    </section>
    <section className="shelf-intro section-shell" data-reveal><p className="eyebrow">A shelf, thoughtfully gathered</p><h2>Many hands.<br /><em>So many lovely cups.</em></h2><div><p>India has a whole world of coffee to discover. This is a small, growing collection of beans and independent roasters to explore while our own café takes shape.</p><p>These are their coffees, gathered here with our brewing suggestions. Follow what sounds like you, and buy directly from the people roasting it.</p></div></section>
    <section className="shelf-roast-guide section-shell" aria-labelledby="roast-heading"><p className="eyebrow">First, find your shade</p><h2 id="roast-heading">A little lighter. <em>A little deeper.</em></h2><div className="roast-stories">{[
      ['Light', 'Bright & expressive', 'Often more fruit, flowers, and lively acidity. A lovely direction for curious filter drinkers.'],
      ['Medium', 'Round & easygoing', 'Often a balance of fruit and developed sweetness. A comfortable place to start exploring.'],
      ['Dark', 'Deep & lingering', 'More roast character, body, and bitterness. For a cup with a bolder, darker edge.'],
    ].map(([name, title, copy], i) => <article key={name} data-reveal><span className={`roast-bean roast-bean-${i}`} aria-hidden="true" /><span className="eyebrow">0{i + 1} / {name}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="shelf-caption">Roast is only part of the story. Origin, processing, and brewing change the cup too. “Filter” describes a roast’s intended brew style, not a universal colour.</p></section>
    <section className="shelf-beans section-shell" id="beans" aria-labelledby="beans-heading"><div className="shelf-section-top"><div><p className="eyebrow">The bean collection</p><h2 id="beans-heading">A cup for <em>your kind of day.</em></h2></div><a href="#roasters">Explore all 9 sellers <Arrow /></a></div><p className="shelf-notes">Chocolate, honey, fruit: these are tasting impressions, not added ingredients. Our featured selection is plain coffee, for brewing without milk or sugar.</p>
      <div className="shelf-filters"><div className="shelf-filter-buttons" role="group" aria-label="Filter by roast">{[['all', 'All roasts'], ['light', 'Light'], ['medium', 'Medium'], ['dark', 'Medium-dark & dark'], ['filter', 'Filter']].map(([id, label]) => <button key={id} aria-pressed={roast === id} onClick={() => setRoast(id)}>{label}</button>)}</div><label>Roaster<select value={seller} onChange={e => setSeller(e.target.value)}><option value="all">All featured roasters</option>{[...new Set(beans.map(b => b.seller))].map(name => <option key={name}>{name}</option>)}</select></label></div><p className="shelf-caption" role="status">{visible.length} {visible.length === 1 ? 'coffee' : 'coffees'} to explore</p>
      <div className="bean-grid">{visible.map(bean => <article className={`bean-card bean-card-${bean.tone}`} key={bean.id}><div className="bean-card-top"><span className="eyebrow">{bean.seller}</span><span>{bean.roast} roast</span></div><div className="bean-emblem" aria-hidden="true"><span className="roast-bean" /><i /><i /></div><p className="shelf-caption">{bean.origin}</p><h3>{bean.name}</h3><p className="bean-notes">{bean.notes}</p><p className="bean-thought">{bean.thought}</p><div className="bean-card-bottom"><span>{bean.process}</span><a href={bean.url} target="_blank" rel="noreferrer">Shop at {bean.seller} <Arrow /></a></div></article>)}</div>
      {visible.length === 0 && <div className="shelf-empty"><h3>A different shade, perhaps?</h3><p>No featured beans match this combination yet.</p><button onClick={() => { setRoast('all'); setSeller('all'); }}>Show all coffees</button></div>}
      <p className="shelf-caption">Roast and tasting descriptions come from the roasters; brew pairings are our editorial starting points, not personal tasting reviews. External shop links open a new tab. Availability, ingredients, grind options, delivery, and prices are confirmed on the seller’s site.</p>
    </section>
    <section className="shelf-grind section-shell" id="grind" aria-labelledby="grind-heading"><div><p className="eyebrow">The small detail that changes the cup</p><h2 id="grind-heading">Right bean.<br /><em>Right grind.</em></h2><p>Choose the cup you want to make. We’ll help with a starting grind and two directions to explore.</p><label htmlFor="shelf-brew">I’m making<select id="shelf-brew" value={brewId} onChange={e => setBrewId(e.target.value)}>{coffees.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="shelf-caption">Have a grinder? Choose whole beans. Otherwise, select your brewing method on the roaster’s site. Their named grind options are more useful than a universal grinder number.</p></div><div className="grind-result" aria-live="polite"><svg viewBox="0 0 300 140" aria-hidden="true">{Array.from({ length: 140 }, (_, i) => <circle key={i} cx={15 + (i * 47 % 270)} cy={12 + (i * 31 % 116)} r={particleSize * (.4 + (i % 4) / 5)} fill="currentColor" />)}</svg><span className="eyebrow">Your starting grind</span><h3>{coffee.grind}</h3><p>For {coffee.name.toLowerCase()} · {coffee.time}</p><div className="grind-matches">{recommended.map(b => <a key={b.id} href={b.url} target="_blank" rel="noreferrer"><span><small>{b.seller}</small>{b.name}</span><Arrow /></a>)}</div><p className="shelf-caption">Grind illustration is indicative. Adjust to your equipment and taste.</p></div></section>
    <section className="shelf-directory section-shell" id="roasters"><p className="eyebrow">Keep wandering / The Indian roaster directory</p><h2>There’s a whole world<br /><em>in our own backyard.</em></h2><p>More shelves, more origins, more people putting their care into coffee. Explore each seller’s current collection; choose plain, unflavoured coffee for our water-only rituals.</p><div>{roasters.map((r, i) => <a href={r.url} key={r.name} target="_blank" rel="noreferrer"><span className="eyebrow">{String(i + 1).padStart(2, '0')}</span><h3>{r.name}</h3><p>{r.note}</p><Arrow /></a>)}</div><p className="shelf-caption">Independent links, with no affiliate tracking or paid placements. CoffeeMasiha does not sell or fulfil these products. Listings reviewed September 2026; seasonal collections change.</p></section>
    <footer className="shelf-footer section-shell"><span className="bean-mark" aria-hidden="true" /><h2>The dream is growing.<br /><em>One cup at a time.</em></h2><a className="shelf-link" href="/#cups">Back to our brewing rituals <Arrow /></a><span className="shelf-caption">CoffeeMasiha · A personal dream by Mohnish</span></footer>
  </div>;
}
